export const careerApplyNowContent = {
  heading: "Apply and Schedule an Interview",
  contact: {
    phone: {
      label: "call us on our {hr}",
      number: "+91 63520 11266",
      href: "tel:+916352011266",
    },
    email: {
      label: "DROP YOUR RESUME AT :",
      address: "hr@dynamicdreamz.com",
      href: "mailto:hr@dynamicdreamz.com",
    },
  },
  positions: [
    "Technical Content Writer",
    "Magento Developer",
    "Mern Stack Developer",
    "Business Development Executive (BDE)",
    "Customer Relationship Executive (CRE)",
    "Pre-Sale Business Analyst",
    "Shopify Front End Developer",
    "Shopify Back End Developer",
    "WordPress Front End Developer",
    "WordPress Back End Developer",
    "Laravel Developer",
    "Full Stack Developer",
    "Freshers/ Interns",
    "Web Designer",
    "Client Relationship Executive",
    "UI/UX Designer",
    "HR Recruiter",
    "PHP Developer",
    "QA Tester",
    "React Native",
    "Outbound Sales Executive",
    "LinkedIn Growth Executive",
    "Conversion Rate Optimization (CRO)",
    "SEO, AEO and GEO",
    "Performance Marketing Specialist",
  ],
  locations: ["Surat", "Ahmedabad"],
} as const;
