export const caseStudiesUiCopy = {
  empty: "No case studies match your search criteria. Try adjusting your search or filter.",
  loadingMore: "Loading more case studies…",
  end: "You’ve reached the end of the case studies.",
  searchLabel: "Search case studies",
  searchPlaceholder: "Search case studies…",
  allTechnologies: "All Technologies",
  allIndustries: "All Industries",
  clearFilters: "Clear all filters",
  viewCaseStudy: "view Case study",
  goBack: "Go back",
  colors: "Colors",
  typeface: "Typeface",
  visitWebsite: "Visit Website",
  exploreCaseStudy: "explore case study",
  facts: {
    project: "Project",
    industry: "Industry",
    technology: "Technology",
    location: "Location",
  },
  keyMetricsHeading: "Key Metrics / Project Facts",
  challengeEyebrow: "Client Challenge / Objective",
  challengeHeading: "What the Project Needed to Solve",
  solutionsEyebrow: "Our Solution",
  solutionsHeading: "How We Approached the Project",
  featuresEyebrow: "Key Features",
  featuresHeading: "Key Features Delivered",
  deliveryEyebrow: "Key Features",
  deliveryHeading: "Project Delivery & Technology",
  serviceDelivered: "Service Delivered",
  relatedEyebrow: "RELATED CASE STUDIES",
  relatedHeading: "Explore Our Client Case Studies",
  relatedDescription:
    "See how Dynamic Dreamz approaches Shopify and Shopify Plus requirements across redesigns, custom commerce, integrations and long-term development partnerships.",
  showing: "Showing",
  project: "project",
  projects: "projects",
} as const;
