export const migrationSectionCopy = {
  brandsHeading: "Trusted by Leading Brands",
  brandsAriaLabel: "Trusted Brands",
  testimonialsHeading: "Our Customer's Testimonials",
  testimonialsDescription:
    "We have faith in our work, but what truly matters is the outcomes we serve our clients. <br> Happy clients make happy stories: Check out how our services empower them to evolve.",
} as const;

export const brandTrustAriaLabels: Readonly<Record<string, string>> = {
  "android-app-development": "Trusted Brands",
  "astra-theme-customization": "Brands that trust Dynamic Dreamz for Astra theme customization",
  "atelier-theme-customization": "Brands that trust Dynamic Dreamz for Atelier theme customization",
  "be-yours-theme-customization": "Brands that trust Dynamic Dreamz for Be Yours theme customization",
  "bigcommerce-development": "Trusted Brands",
  "bigcommerce-to-shopify-migration": "Brands that trust Dynamic Dreamz for BigCommerce to Shopify migration",
  "blocksy-theme-customization": "Brands that trust Dynamic Dreamz for Blocksy theme customization",
  "bloghash-theme-customization": "Brands that trust Dynamic Dreamz for BlogHash theme customization",
  "broadcast-theme-customization": "Brands that trust Dynamic Dreamz for Broadcast theme customization",
  "case-studies": "Brands featured in Dynamic Dreamz case studies",
  "colorblock-theme-customization": "Brands that trust Dynamic Dreamz for Colorblock theme customization",
  "craft-theme-customization": "Brands that trust Dynamic Dreamz for Craft theme customization",
  "cross-platform-app-development": "Trusted Brands",
  "dawn-theme-customization": "Brands that trust Dynamic Dreamz for Dawn theme customization",
  "dental-clinic-website-development-company": "Brands that trust Dynamic Dreamz for dental clinic website development",
  "dwell-theme-customization": "Brands that trust Dynamic Dreamz for Dwell theme customization",
  "ecwid-to-shopify-migration": "Brands that trust Dynamic Dreamz for Ecwid to Shopify migration",
  "etsy-to-shopify-migration": "Brands that trust Dynamic Dreamz for Etsy to Shopify migration",
  "extendable-theme-customization": "Brands that trust Dynamic Dreamz for Extendable theme customization",
  "fabric-theme-customization": "Brands that trust Dynamic Dreamz for Fabric theme customization",
  "generatepress-theme-customization": "Brands that trust Dynamic Dreamz for GeneratePress theme customization",
  "go-theme-customization": "Brands that trust Dynamic Dreamz for Go theme customization",
  "hello-biz-theme-customization": "Brands that trust Dynamic Dreamz for Hello Biz theme customization",
  "hello-elementor-theme-customization": "Brands that trust Dynamic Dreamz for Hello Elementor theme customization",
  "heritage-theme-customization": "Brands that trust Dynamic Dreamz for Heritage theme customization",
  "hire-shopify-developers": "Brands that trust Dynamic Dreamz for Shopify development",
  "hire-wordpress-developers": "Brands that trust Dynamic Dreamz for web development",
  "impact-theme-customization": "Brands that trust Dynamic Dreamz for Impact theme customization",
  "impulse-theme-customization": "Brands that trust Dynamic Dreamz for Impulse theme customization",
  "ios-app-development": "Trusted Brands",
  "kadence-theme-customization": "Brands that trust Dynamic Dreamz for Kadence theme customization",
  "kubio-theme-customization": "Brands that trust Dynamic Dreamz for Kubio theme customization",
  "magento-development": "Trusted Brands",
  "magento-to-shopify-migration": "Brands that trust Dynamic Dreamz for Magento to Shopify migration",
  "magento-to-shopify-plus-migration": "Brands that trust Dynamic Dreamz for Magento to Shopify Plus migration",
  "mobile-application-development": "Trusted Brands",
  "neve-theme-customization": "Brands that trust Dynamic Dreamz for Neve theme customization",
  "newsblogger-theme-customization": "Brands that trust Dynamic Dreamz for NewsBlogger theme customization",
  "oceanwp-theme-customization": "Brands that trust Dynamic Dreamz for OceanWP theme customization",
  "origin-theme-customization": "Brands that trust Dynamic Dreamz for Origin theme customization",
  "our-work": "Brands featured in the Dynamic Dreamz portfolio",
  "pipeline-theme-customization": "Brands that trust Dynamic Dreamz for Pipeline theme customization",
  "pitch-theme-customization": "Brands that trust Dynamic Dreamz for Pitch theme customization",
  "popularfx-theme-customization": "Brands that trust Dynamic Dreamz for PopularFX theme customization",
  "prestashop-to-shopify-migration": "Brands that trust Dynamic Dreamz for PrestaShop to Shopify migration",
  "prestige-theme-customization": "Brands that trust Dynamic Dreamz for Prestige theme customization",
  "publisher-theme-customization": "Brands that trust Dynamic Dreamz for Publisher theme customization",
  "refresh-theme-customization": "Brands that trust Dynamic Dreamz for Refresh theme customization",
  "ritual-theme-customization": "Brands that trust Dynamic Dreamz for Ritual theme customization",
  "royal-elementor-kit-theme-customization": "Brands that trust Dynamic Dreamz for Royal Elementor Kit theme customization",
  "salesforce-to-shopify-migration": "Brands that trust Dynamic Dreamz for Salesforce to Shopify migration",
  "savor-theme-customization": "Brands that trust Dynamic Dreamz for Savor theme customization",
  "sense-theme-customization": "Brands that trust Dynamic Dreamz for Sense theme customization",
  "shopify-development-agency": "Brands that trust Dynamic Dreamz",
  "shopify-development-company-in-chennai": "Brands that trust Dynamic Dreamz for Shopify development in Chennai",
  "shopify-development-in-delhi": "Brands that trust Dynamic Dreamz for Shopify development in Delhi",
  "shopify-maintenance-services": "Brands that trust Dynamic Dreamz for Shopify maintenance services",
  "shopify-mobile-app-development": "Trusted Brands",
  "shopify-plus-agency": "Brands that trust Dynamic Dreamz",
  "shopify-plus-migration-agency": "Brands that trust Dynamic Dreamz for Shopify Plus migration",
  "shopify-theme-customization": "Brands that trust Dynamic Dreamz for Shopify theme customization",
  "spotlight-theme-customization": "Brands that trust Dynamic Dreamz for Spotlight theme customization",
  "square-to-shopify-migration": "Brands that trust Dynamic Dreamz for Square to Shopify migration",
  "squarespace-to-shopify-migration": "Brands that trust Dynamic Dreamz for Squarespace to Shopify migration",
  "startup-theme-customization": "Brands that trust Dynamic Dreamz for Startup theme customization",
  "stiletto-theme-customization": "Brands that trust Dynamic Dreamz for Stiletto theme customization",
  "studio-theme-customization": "Brands that trust Dynamic Dreamz for Studio theme customization",
  "tinker-theme-customization": "Brands that trust Dynamic Dreamz for Tinker theme customization",
  "trade-theme-customization": "Brands that trust Dynamic Dreamz for Trade theme customization",
  "vision-theme-customization": "Brands that trust Dynamic Dreamz for Vision theme customization",
  "warehouse-theme-customization": "Brands that trust Dynamic Dreamz for Warehouse theme customization",
  "web-design": "Trusted Brands",
  "webflow-development": "Trusted Brands",
  "wix-to-shopify-migration": "Brands that trust Dynamic Dreamz for Wix to Shopify migration",
  "woocommerce-to-shopify-migration": "Brands that trust Dynamic Dreamz for WooCommerce to Shopify migration",
  "woodstock-theme-customization": "Brands that trust Dynamic Dreamz for Woodstock theme customization",
  "wordpress-theme-customization": "Brands that trust Dynamic Dreamz for WordPress theme customization",
};

export const migrationHeroBadges = [
  {
    name: "Shopify Platinum Partner",
    src: "/assets/proof/shopify-platinum-partner.svg",
    href: "https://www.shopify.com/partners/directory/partner/dynamic-dreamz",
    alt: "Dynamic Dreamz - Shopify Platinum Partner",
    width: 136,
    height: 44,
  },
  {
    name: "Clutch",
    src: "/assets/proof/clutch-rating.svg",
    href: "https://clutch.co/profile/dynamic-dreamz",
    alt: "Dynamic Dreamz on Clutch — 4.9 rating",
    width: 111,
    height: 44,
  },
  {
    name: "Trustpilot",
    src: "/assets/proof/trustpilot-rating.svg",
    href: "https://www.trustpilot.com/review/dynamicdreamz.com",
    alt: "Dynamic Dreamz on Trustpilot — 4.9 TrustScore",
    width: 148,
    height: 50,
  },
  {
    name: "Upwork",
    src: "/assets/proof/upwork-top-rated-plus.svg",
    href: "https://www.upwork.com/ag/dynamicdreamz/",
    alt: "Dynamic Dreamz — Upwork Top Rated Plus",
    width: 148,
    height: 40,
  },
] as const;

export const migrationBrandLogos = [
  {
    href: "https://supertails.com/",
    src: "/assets/clients/supertails.svg",
    alt: "Supper Tails Logo",
    width: 164,
    height: 41,
  },
  {
    href: "https://11-11.in/",
    src: "/assets/clients/eleven-eleven.svg",
    alt: "Eleven Eleven",
    width: 145,
    height: 20,
  },
  {
    href: "https://bellavitaorganic.com/",
    src: "/assets/clients/bella-vita.svg",
    alt: "bellavita logo",
    width: 166,
    height: 24,
  },
  {
    href: "https://www.bombayshirts.com/",
    src: "/assets/clients/bombay-shirt-company.svg",
    alt: "Bombay Shirt Company",
    width: 204,
    height: 26,
  },
  {
    href: "https://popclub.co/",
    src: "/assets/clients/popclub.svg",
    alt: "",
    width: 65,
    height: 41,
  },
  {
    href: "https://www.srisritattva.com/",
    src: "/assets/clients/sri-sri-tattva.svg",
    alt: "SriSri Tattva Logo",
    width: 106,
    height: 40,
  },
  {
    href: "https://shop.tropicfeel.com/",
    src: "/assets/clients/tropicfeel.svg",
    alt: "tropicfeel logo",
    width: 150,
    height: 32,
  },
  {
    href: "https://www.reneecosmetics.in/",
    src: "/assets/clients/renee.svg",
    alt: "Renee logo",
    width: 93,
    height: 30,
  },
  {
    href: "https://royceindia.com/",
    src: "/assets/clients/royce-chocolate.svg",
    alt: "Royce chocolate logo",
    width: 132,
    height: 38,
  },
  {
    href: "https://tego.fit/",
    src: "/assets/clients/tego.svg",
    alt: "tego logo",
    width: 101,
    height: 40,
  },
  {
    href: "https://www.nekterjuicebar.com/",
    src: "/assets/clients/nekter-colored.svg",
    alt: "nekter-colored",
    width: 66,
    height: 64,
  },
  {
    href: "https://thehouseofrare.com/",
    src: "/assets/clients/rare-rabbit.svg",
    alt: "Rare Rabbit Logo",
    width: 122,
    height: 84,
  },
] as const;
