export const migrationSectionCopy = {
  brandsHeading: "Trusted by Leading Brands",
  brandsAriaLabel: "Trusted Brands",
  testimonialsHeading: "Our Customers' Testimonials",
  testimonialsDescription:
    "We have faith in our work, but what truly matters is the outcomes we serve our clients. <br> Happy clients make happy stories: Check out how our services empower them to evolve.",
} as const;

export const brandTrustAriaLabels: Readonly<Record<string, string>> = {
  "android-app-development": "Trusted Brands",
  "astra-theme-customization": "Brands that trust Dynamic Dreamz for Astra theme customization",
  "atelier-theme-customization": "Brands that trust Dynamic Dreamz for Atelier theme customization",
  "be-yours-theme-customization": "Brands that trust Dynamic Dreamz for Be Yours theme customization",
  "bigcommerce-development": "Trusted Brands",
  "blocksy-theme-customization": "Brands that trust Dynamic Dreamz for Blocksy theme customization",
  "bloghash-theme-customization": "Brands that trust Dynamic Dreamz for BlogHash theme customization",
  "broadcast-theme-customization": "Brands that trust Dynamic Dreamz for Broadcast theme customization",
  "case-studies": "Brands featured in Dynamic Dreamz case studies",
  "colorblock-theme-customization": "Brands that trust Dynamic Dreamz for Colorblock theme customization",
  "craft-theme-customization": "Brands that trust Dynamic Dreamz for Craft theme customization",
  "cross-platform-app-development": "Trusted Brands",
  "dawn-theme-customization": "Brands that trust Dynamic Dreamz for Dawn theme customization",
  "dental-clinic-website-development-company": "Brands that trust Dynamic Dreamz for dental clinic website development",
  "dwell-theme-customization": "Brands that trust Dynamic Dreamz for Dwell theme customization",
  "ecwid-to-shopify-migration": "Brands that trust Dynamic Dreamz for Ecwid to Shopify migration",
  "etsy-to-shopify-migration": "Brands that trust Dynamic Dreamz for Etsy to Shopify migration",
  "extendable-theme-customization": "Brands that trust Dynamic Dreamz for Extendable theme customization",
  "fabric-theme-customization": "Brands that trust Dynamic Dreamz for Fabric theme customization",
  "generatepress-theme-customization": "Brands that trust Dynamic Dreamz for GeneratePress theme customization",
  "go-theme-customization": "Brands that trust Dynamic Dreamz for Go theme customization",
  "hello-biz-theme-customization": "Brands that trust Dynamic Dreamz for Hello Biz theme customization",
  "hello-elementor-theme-customization": "Brands that trust Dynamic Dreamz for Hello Elementor theme customization",
  "heritage-theme-customization": "Brands that trust Dynamic Dreamz for Heritage theme customization",
  "hire-shopify-developers": "Brands that trust Dynamic Dreamz for Shopify development",
  "hire-wordpress-developers": "Brands that trust Dynamic Dreamz for web development",
  "impact-theme-customization": "Brands that trust Dynamic Dreamz for Impact theme customization",
  "impulse-theme-customization": "Brands that trust Dynamic Dreamz for Impulse theme customization",
  "ios-app-development": "Trusted Brands",
  "kadence-theme-customization": "Brands that trust Dynamic Dreamz for Kadence theme customization",
  "kubio-theme-customization": "Brands that trust Dynamic Dreamz for Kubio theme customization",
  "magento-development": "Trusted Brands",
  "magento-to-shopify-migration": "Brands that trust Dynamic Dreamz for Magento to Shopify migration",
  "magento-to-shopify-plus-migration": "Brands that trust Dynamic Dreamz for Magento to Shopify Plus migration",
  "mobile-application-development": "Trusted Brands",
  "neve-theme-customization": "Brands that trust Dynamic Dreamz for Neve theme customization",
  "newsblogger-theme-customization": "Brands that trust Dynamic Dreamz for NewsBlogger theme customization",
  "oceanwp-theme-customization": "Brands that trust Dynamic Dreamz for OceanWP theme customization",
  "origin-theme-customization": "Brands that trust Dynamic Dreamz for Origin theme customization",
  "our-work": "Brands featured in the Dynamic Dreamz portfolio",
  "pipeline-theme-customization": "Brands that trust Dynamic Dreamz for Pipeline theme customization",
  "pitch-theme-customization": "Brands that trust Dynamic Dreamz for Pitch theme customization",
  "popularfx-theme-customization": "Brands that trust Dynamic Dreamz for PopularFX theme customization",
  "prestashop-to-shopify-migration": "Brands that trust Dynamic Dreamz for PrestaShop to Shopify migration",
  "prestige-theme-customization": "Brands that trust Dynamic Dreamz for Prestige theme customization",
  "publisher-theme-customization": "Brands that trust Dynamic Dreamz for Publisher theme customization",
  "refresh-theme-customization": "Brands that trust Dynamic Dreamz for Refresh theme customization",
  "ritual-theme-customization": "Brands that trust Dynamic Dreamz for Ritual theme customization",
  "royal-elementor-kit-theme-customization": "Brands that trust Dynamic Dreamz for Royal Elementor Kit theme customization",
  "salesforce-to-shopify-migration": "Brands that trust Dynamic Dreamz for Salesforce to Shopify migration",
  "savor-theme-customization": "Brands that trust Dynamic Dreamz for Savor theme customization",
  "sense-theme-customization": "Brands that trust Dynamic Dreamz for Sense theme customization",
  "shopify-development-agency": "Brands that trust Dynamic Dreamz",
  "shopify-development-company-in-chennai": "Brands that trust Dynamic Dreamz for Shopify development in Chennai",
  "shopify-development-in-delhi": "Brands that trust Dynamic Dreamz for Shopify development in Delhi",
  "shopify-maintenance-services": "Brands that trust Dynamic Dreamz for Shopify maintenance services",
  "shopify-mobile-app-development": "Trusted Brands",
  "shopify-plus-agency": "Brands that trust Dynamic Dreamz",
  "shopify-plus-migration-agency": "Brands that trust Dynamic Dreamz for Shopify Plus migration",
  "shopify-theme-customization": "Brands that trust Dynamic Dreamz for Shopify theme customization",
  "spotlight-theme-customization": "Brands that trust Dynamic Dreamz for Spotlight theme customization",
  "square-to-shopify-migration": "Brands that trust Dynamic Dreamz for Square to Shopify migration",
  "squarespace-to-shopify-migration": "Brands that trust Dynamic Dreamz for Squarespace to Shopify migration",
  "startup-theme-customization": "Brands that trust Dynamic Dreamz for Startup theme customization",
  "stiletto-theme-customization": "Brands that trust Dynamic Dreamz for Stiletto theme customization",
  "studio-theme-customization": "Brands that trust Dynamic Dreamz for Studio theme customization",
  "tinker-theme-customization": "Brands that trust Dynamic Dreamz for Tinker theme customization",
  "trade-theme-customization": "Brands that trust Dynamic Dreamz for Trade theme customization",
  "vision-theme-customization": "Brands that trust Dynamic Dreamz for Vision theme customization",
  "warehouse-theme-customization": "Brands that trust Dynamic Dreamz for Warehouse theme customization",
  "web-design": "Trusted Brands",
  "wix-to-shopify-migration": "Brands that trust Dynamic Dreamz for Wix to Shopify migration",
  "woocommerce-to-shopify-migration": "Brands that trust Dynamic Dreamz for WooCommerce to Shopify migration",
  "woodstock-theme-customization": "Brands that trust Dynamic Dreamz for Woodstock theme customization",
  "wordpress-theme-customization": "Brands that trust Dynamic Dreamz for WordPress theme customization",
};
